### ISSUE TITLE
[Enhancement] Downloading Suggestions

### ISSUE THREAD

**Issue by DarkCrypt** [supersu-man/hymn#2]
This app is awesome because of your new improvements in v1.2.0! I like the added function to play songs and switching from ytdl to new pipe was a complete game changer. Very smart move, downloads are lightning fast as in 1-2sec. So fast that if you're not paying attention when you hit download you'll miss the entire process and wonder if the file downloaded. I've done this a few times so I checked the download folder to make sure the function worked. After doing this a few times I started paying more attention when I hit download.

Because of these reasons I'm suggesting the following possible enhancements:
1. Include an outside download notification so users know when a file is downloaded and then they can manually close it out.
2. Or if (1) isn't desirable, improve the in-app downloader to let users know when download is complete and then the user can manually close instead of disappearing without confirmation.
3. Implement multiple select to enable downloading multiple songs at a time or even just 1 song.

After using your new build, I'm curious to what future enhancements you have planned.

**Comment by supersu-man** [comment]
Thank you for the suggestion.
Right now I am working on another major feature and few UI improvements.
Will add the suggested feature after this is done.

**Comment by DarkCrypt** [comment]
You're welcome friend. Thank you for your time, hard work, and dedication to this app. I'm already looking forward to the next release.

**Comment by supersu-man** [comment]
Added download complete dialog in [v1.2.1](https://github.com/supersu-man/hymn/releases/tag/v1.2.1)
