### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by saweeet** [supersu-man/hymn#3]
Says downloaded but cannot find it in storage. Might be a permission error? APP > Info says no permissions required. Running Android 13.

**Comment by DarkCrypt** [comment]
@supersu-man

Same for me, download not working on Android 13.

**Comment by supersu-man** [comment]
@saweeet @DarkCrypt Do check out [1.2.2](https://github.com/supersu-man/hymn/releases/tag/v1.2.2) Release and let me know if it works.

**Comment by DarkCrypt** [comment]
V1.2.2 is working for me.
